
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/board
@boardId = {{ login.response.body.$.data.boardId }}
@token = {{ auth.response.body.$.data.token }}
# @sensorId = {{ devices.response.body.$.data.sensors[0].sensor }}
@sensorId = 605a777cd499e0fe47df8bd4
# @relayId = {{ devices.response.body.$.data.relays[0].relay }}
@relayId = 5f5d430dcee4131df705241e

### AUTH
# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "board": "605a717d8dc961db9ef17720",
	"password": "bgwK7pDqFviZQBLv"
}

### GET DEVICES
# @name devices
GET {{baseUrl}}/devices
Authorization: Bearer {{token}}


### INSERT SENSOR TS DATA
POST {{baseUrl}}/ts/sensor/{{sensorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
  "value": 3000,
  "resolution": 4095
}


### INSERT RELAY TS DATA
POST {{baseUrl}}/ts/relay/{{relayId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "value": true }