
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/board
@boardId = {{ login.response.body.$.data.boardId }}
@token = {{ auth.response.body.$.data.token }}
@sensorId = {{ devices.response.body.$.data.sensors[0].sensor }}

### AUTH
# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "board": "5f30af651edba91d74deeb81",
	"password": "+p-u7Ln3g=LEbEyJ"
}

### GET DEVICES
# @name devices
GET {{baseUrl}}/device
Authorization: Bearer {{token}}


### INSERT TS DATA
POST {{baseUrl}}/ts/{{sensorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "value": 100 }