
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/board
@boardId = {{ login.response.body.$.data.boardId }}
@token = {{ auth.response.body.$.data.token }}
@sensorId = {{ devices.response.body.$.data.sensors[0].sensor }}
# @relayId = {{ devices.response.body.$.data.relays[0].relay }}
@relayId = 5f5d430dcee4131df705241e

### AUTH
# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "board": "5f4da2347c14b1d12aa9601f",
	"password": "M09OJYWXf3A4&7vk"
}

### GET DEVICES
# @name devices
GET {{baseUrl}}/devices
Authorization: Bearer {{token}}


### INSERT SENSOR TS DATA
POST {{baseUrl}}/ts/sensor/{{sensorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
  "value": 2000,
  "resolution": 4095
}


### INSERT RELAY TS DATA
POST {{baseUrl}}/ts/relay/{{relayId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "value": true }