
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/projects
@projectId = {{ projects.response.body.$.data[0]._id }}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjFhMzU4ZDE2YTYzNTY2YWMxNGU0MGEiLCJpYXQiOjE1OTU1NTMxNzMsImV4cCI6MTU5NjE1Nzk3M30.0wO_PC7gFcV9B6WjiyS2BoMGBfjdoCjB46NGp_cMMCQ

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project One",
  "privacy": "public"
}


### GET ALL PROJECTS
# @name projects
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET PROJECT BY ID
GET {{baseUrl}}/{{projectId}}
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project One",
  "description": "Project created for test purposes only",
  "privacy": "private",
  "users": ["5f1a35bc16a63566ac14e40b","5f1a35c616a63566ac14e40c"]
}


### REMOVE
DELETE {{baseUrl}}/{{projectId}}
Authorization: Bearer {{token}}
