
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@projectId = 5f4da1ff7c14b1d12aa9601e
@thingId = 5f652b1ccdbcd52003a7dce4
@baseUrl = http://{{host}}:{{port}}/api/project/{{projectId}}/thing/{{thingId}}/relay
# @relayId = {{ relays.response.body.$.data[0]._id }}
@relayId = 5f652c49cdbcd52003a7dce5
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjRkOGVhOGU0MzU1ZWEwYmVjOWUxOTYiLCJpYXQiOjE2MDA2MjAyMzYsImV4cCI6MTYwMTIyNTAzNn0.ZTbOixilwEHC-EoVnb0VWjPj3RUZ04LjxdOQo0znPbo

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "Light 1",
	"pin" : 2,
	"store" : true
}


### GET ALL RELAYS
# @name relays
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET RELAY BY ID
GET {{baseUrl}}/{{relayId}}
Authorization: Bearer {{token}}


### GET TS DATA
GET {{baseUrl}}/{{relayId}}/ts
# GET {{baseUrl}}/{{relayId}}/ts?start=2020-09-12T03:00:30.000Z&end=2020-09-13T03:00:30.000Z
Content-Type: application/json
Authorization: Bearer {{token}}


### INSERT RELAY TS DATA
POST {{baseUrl}}/{{relayId}}/ts
Authorization: Bearer {{token}}
Content-Type: application/json

{ "value": true }


### GET VALUE
GET {{baseUrl}}/{{relayId}}/value
Content-Type: application/json
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{relayId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "Light 1",
	"pin" : 16,
	"store" : true
}


### DISCARD UPCOMING CHANGES
PATCH {{baseUrl}}/{{relayId}}/discardUpcomingChanges
Content-Type: application/json
Authorization: Bearer {{token}}


### REMOVE
DELETE {{baseUrl}}/{{relayId}}
Authorization: Bearer {{token}}
