
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/sensortype
@sensorTypeId = {{ sensorTypes.response.body.$.data[0]._id }}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjRkOGVhOGU0MzU1ZWEwYmVjOWUxOTYiLCJpYXQiOjE2MTYyNjE3MDQsImV4cCI6MTYxNjg2NjUwNH0._V54MIKL8vMwaX4cDlYIqAxjO-IyRA5EXKz9U6EvUDQ

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type" : "Thermistor NTC",
	"input" : "Analog",
	"config" : [
		{
      "parameter": "Rn",
			"description" : "Nominal resistance of NTC at nominal temperature",
			"default" : 10000
		},
		{
      "parameter": "Tn",
			"description" : "Nominal temperature",
			"default" : 25
		},
		{
      "parameter": "beta",
			"description" : "Beta",
			"default" : 4300
		},
		{
      "parameter": "Rs",
			"description" : "Series resistor",
			"default" : 10000
		}
	],
	"function" : "var resistance = ((resolution*10000/value) - Rn);\nvar temperature = resistance / Rn;\ntemperature = Math.log(temperature);\ntemperature /= beta;\ntemperature += 1.0 / (Tn + 273.15);\ntemperature = 1 / temperature;\ntemperature -= 273.15;\n return temperature;"
}
### {
###   "type" : "General Analog Sensor",
### 	"input" : "Analog"
### }
### {
###   "type" : "Lighting",
### 	"input" : "Analog",
### 	"config" : [
### 		{
###       "parameter": "L",
### 			"description" : "Lighting index based on board reading (in percent)",
### 			"default" : 30
### 		}
### 	],
### 	"function" : "const result = (value/resolution) * 100;\nif (result >= L) { \n  return true;\n} else { \n  return false;\n}\n"
### }


### GET ALL SENSOR TYPES
# @name sensorTypes
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET SENSOR TYPE BY ID
GET {{baseUrl}}/{{sensorTypeId}}
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{sensorTypeId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type" : "Thermistor NTC10K",
	"input" : "Analog",
	"config" : [
		{
      "parameter": "Rn",
			"description" : "Nominal resistance of NTC at nominal temperature",
			"default" : 10000
		},
		{
      "parameter": "Tn",
			"description" : "Nominal temperature",
			"default" : 25
		},
		{
      "parameter": "beta",
			"description" : "Beta",
			"default" : 4300
		},
		{
      "parameter": "Rs",
			"description" : "Series resistor",
			"default" : 10000
		}
	],
	"function" : "var resistance = ((resolution*10000/value) - Rn);\nvar temperature = resistance / Rn;\ntemperature = Math.log(temperature);\ntemperature /= beta;\ntemperature += 1.0 / (Tn + 273.15);\ntemperature = 1 / temperature;\ntemperature -= 273.15;\n return temperature;"
}


### REMOVE
DELETE {{baseUrl}}/{{sensorTypeId}}
Authorization: Bearer {{token}}
