
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@projectId = 5f4da1ff7c14b1d12aa9601e
@thingId = 5f4da2347c14b1d12aa9601f
@baseUrl = http://{{host}}:{{port}}/api/project/{{projectId}}/thing/{{thingId}}/sensor
# @sensorId = {{ sensors.response.body.$.data[0]._id }}
@sensorId = 5f4ea296588fdf289fcdac59
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjRkOGVhOGU0MzU1ZWEwYmVjOWUxOTYiLCJpYXQiOjE1OTkwMDEzNDUsImV4cCI6MTU5OTYwNjE0NX0.tiOy9vUb-8XIZQHHGS2MV8n6_pduSNHiKxwZSansdwY

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "Temperature",
	"type" : "5f1a38b730a249784aa77aad",
	"pin" : 34,
	"pollTime" : 60000,
	"input" : "Analog",
	"store" : true,
	"decimalPlaces" : 1,
	"config" : [
		{
			"parameter": "Rn",
			"value": 10000
		},
		{
			"parameter": "Tn",
			"value": 25
		},
		{
			"parameter": "beta",
			"value": 4300
		},
		{
			"parameter": "Rs",
			"value": 10000
		}
	]
}


### GET ALL SENSORS
# @name sensors
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET SENSOR BY ID
GET {{baseUrl}}/{{sensorId}}
Authorization: Bearer {{token}}


### GET TS DATA
GET {{baseUrl}}/{{sensorId}}/ts?start=2020-08-25T03:00:30.000Z&end=2020-08-29T03:01:30.000Z
Content-Type: application/json
Authorization: Bearer {{token}}


### GET VALUE
GET {{baseUrl}}/{{sensorId}}/value
Content-Type: application/json
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{sensorId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "Temperature NTC10K",
	"type" : "5f162a2cfe0ff3c3d805f1fb",
	"pin" : 34,
	"pollTime" : 30000,
	"input" : "Analog",
	"store" : true,
	"decimalPlaces" : 1,
	"config" : [
		{
			"parameter": "Rn",
			"value": 10000
		},
		{
			"parameter": "Tn",
			"value": 25
		},
		{
			"parameter": "beta",
			"value": 4300
		},
		{
			"parameter": "Rs",
			"value": 10000
		}
	]
}


### REMOVE
DELETE {{baseUrl}}/{{sensorId}}
Authorization: Bearer {{token}}
