# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/things/5f053837466182e665e10074
@thingId = {{ things.response.body.$.data[0]._id }}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZWVlOTU3M2IwMGE1NzRlZjNiNGU1NTMiLCJpYXQiOjE1OTUyODc2MTMsImV4cCI6MTU5NTg5MjQxM30.QWKWCMzQBDHcm-70PV8VlyrfFjbsF8wyQ5UTW0EN8gg


### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-302",
	"type" : "Classroom",
	"sensors": [
		"5f16480ecdc83e5673a39163",
		"5f18d22b7a2128aef50225c5"
	]
}


### GET ALL THINGS
# @name things
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET THING BY ID
GET {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{thingId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-301",
	"type" : "Classroom",
	"sensors": [
		"5f16480ecdc83e5673a39163",
		"5f18d22b7a2128aef50225c5"
	]
}


### REMOVE
DELETE {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}
