# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/things/5f1a35fe16a63566ac14e40d
@thingId = {{ things.response.body.$.data[0]._id }}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjFhMzU4ZDE2YTYzNTY2YWMxNGU0MGEiLCJpYXQiOjE1OTU1NTMxNzMsImV4cCI6MTU5NjE1Nzk3M30.0wO_PC7gFcV9B6WjiyS2BoMGBfjdoCjB46NGp_cMMCQ

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-302",
	"type" : "Classroom"
}


### GET ALL THINGS
# @name things
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET THING BY ID
GET {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{thingId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-301",
	"type" : "Classroom",
}


### REMOVE
DELETE {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}
