# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@projectId = 5f4da1ff7c14b1d12aa9601e
@baseUrl = http://{{host}}:{{port}}/api/project/{{projectId}}/thing
# @thingId = {{ things.response.body.$.data[0]._id }}
@thingId = 5f4da2347c14b1d12aa9601f
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjRkOGVhOGU0MzU1ZWEwYmVjOWUxOTYiLCJpYXQiOjE2MDAzODc5NzMsImV4cCI6MTYwMDk5Mjc3M30.S2SEUuJYHm-3ctigdztke3zAUwe5VxIoS3lPbLY2cKw

### CREATE
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-302",
	"type" : "Classroom"
}


### GET ALL THINGS
# @name things
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET THING BY ID
GET {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}


### GET BOARD STATUS
GET {{baseUrl}}/{{thingId}}/board
Authorization: Bearer {{token}}


### GET ALL THING TYPES
GET {{baseUrl}}/types
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{thingId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name" : "B-301",
	"type" : "Classroom",
}


### REMOVE
DELETE {{baseUrl}}/{{thingId}}
Authorization: Bearer {{token}}
