
# DEV
@host = localhost
@port = 3000

# # HMG
# @host = localhost
# @port = 3001

@baseUrl = http://{{host}}:{{port}}/api/users
@userId = {{ login.response.body.$.data.userId }}
@token = {{ login.response.body.$.data.token }}

### SIGNUP
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "email": "test@test",
  "username": "test",
  "password": "123456"
}


### LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "123456"
}


### GET ALL USERS
GET {{baseUrl}}
Authorization: Bearer {{token}}


### GET USER BY ID
GET {{baseUrl}}/{{userId}}
Authorization: Bearer {{token}}


### UPDATE
PUT {{baseUrl}}/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "_id": "{{userId}}",
  "firstName": "Edited",
  "lastName": "Edited",
  "email": "test@test"
}


### REMOVE
DELETE {{baseUrl}}/{{userId}}
Authorization: Bearer {{token}}
